image: "aparo/sbt-nodejs-docker:1.3.4-12.13.1"

stages:
  - publish
  - pages

allinone:
  stage: publish
  before_script:
    - set
    - cat $CREDENTIALS_SBT > credentials.sbt
    - git config --global user.name $GIT_ACCESS_USER
    - git config --global user.email $GIT_ACCESS_EMAIL
    - git reset --hard
    - git clean -fd
    - git checkout $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME

  script:
#    - sbt clean test publish
    - sbt "release with-defaults"

pages:
  stage: pages
  script:
    - sbt clean coverage test coverageReport coverageOff doc
    - cp -r target/scala-2.13/scoverage-report public/scoverage-report
    - cp -r target/scala-2.13/api public/api
  artifacts:
    paths:
      - public
